### ISSUE TITLE
Error in dirname: object 'project_path' not found

### ISSUE THREAD

**Issue by slockton** [ropenscilabs/qcoder#181] opened 2019-09-25 03:46 UTC
New user, trying out qcoder for the first time. I'm experienced with R and RStudio and Shiny. Using R 3.6.0 on Mac OS 10.14.6. I used the 'tldr' to install and test:

`install.packages("devtools")`
`devtools::install_github("ropenscilabs/qcoder")`
`library(qcoder)`
`create_qcoder_project("my_qcoder_project", sample = TRUE)`
`import_project_data(project = "my_qcoder_project")`
`qcode()`

I chose to update all dependencies. It all installs with no error. And the _my_coder_project_ folder is present within my user folder. When it comes to running qcode(), the shiny app flashes up and crashes with this error:

`Warning: Error in dirname: object 'project_path' not found`
`  51: dirname`
`  47: server [/Users/mlockton/Desktop/qcoder_fix/app.R#480]`
`Error in dirname(project_path) : object 'project_path' not found`

I didn't see anyone else with this error. I've replicated it on another Mac with R 3.6.1.

**Comment by siames3** [comment] 2019-09-25 12:38
It happened to me too in Linux.
I was able to circumvent this by typing project_path <- "my_project.

**Comment by slockton** [comment] 2019-09-25 16:39
Thanks! That worked!

S

**Comment by siames3** [comment] 2019-09-25 18:24
Happy to know that.  It'd be nice if the README instructions worked for everyone, though. 
I find this a really interesting and necessary project. Can't wait to be able to use it!

**Comment by elinw** [comment] 2019-10-03 22:41
We need to update the readme for sure!   I don't think we had a tester on linux -- if you want to send a PR with updated instructions that would be great.

**Comment by elinw** [comment] 2019-10-04 10:07
Here is the documentation for import_project_data():

> Description

> Read data into a project Convenience method to read raw data from standard locations and using standard names in a project folder structure.


> Usage
> 
> import_project_data(project_name)
> 

> project_name | The project name. This should represent the folder holding the project.
> -- | --

>Examples
>create_qcoder_project(project_name = "_my_qcoder_project", sample = TRUE)
>import_project_data("_my_qcoder_project")

Notice that the path is not optional.

**Comment by elinw** [comment] 2019-10-04 10:20
Both of you attempted to do this with sample=TRUE?  Were the rds files created in the dataframes folder when you ran import_project_data()?   Can you also check your working directory to make sure it is the folder your project folder is located in?

**Comment by elinw** [comment] 2019-10-04 10:54
I merged in some changes, can you try updating your installations of qcoder and see if the no project_path issue goes away?

**Comment by elinw** [comment] 2019-10-07 05:58
Updated: did one more fix. Pretty sure it is fixed now

**Comment by elinw** [comment] 2019-10-13 01:40
I'm going to close this since I reproduced the problem and now the problem is gone for me.  If it is still a problem for you on the current master I'm happy to reopen.

**Closed by elinw** 2019-10-13 01:40 UTC
Labels: Awaiting reply
